
[general]
	#The material blacklist of this module.
	materialBlacklist = []

[recipes]
	#The materials that should not have grinder to dust recipes added.
	toDustMaterialBlacklist = []
	#The materials that should not have crusher to plate recipes added.
	toPlateMaterialBlacklist = []
	#The materials that should not have lathe to rod recipes added.
	toRodMaterialBlacklist = []

