
[World]
	#Should Gasoline and Diesel cause explosions when placed next to an ignition source?
	gasolineExplosions = true
	#Should a copy of Assembly Lines & You be distributed to new players?
	#This may be overridden by the client.
	distributeGuideBook = true

[Machines]
	#What is the chance that the Crank will snap when used without a valid recipe?
	crankSnapChance = 0.01
	#Should the Entropy Reactor explode at 98% Entropy?
	reactorExplosions = true
	#Should the fluid bath return Sludge when an invalid recipe is made?
	#If false, both of the component items will instead be returned.
	invalidBathReturnsSludge = true
	#What should the multiplier from stirs or grinds to seconds in the Kinetic Fluid Mixer or Kinetic Grinder be?
	#For example, a recipe taking 10 grinds or stirs would take 15 seconds to process with a multiplier of 1.5.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	kineticMachineCycleModifier = 1.0
	#Should Interact Mode in the Interactor be enabled? Sometimes, this can cause exceptions and other bugs, like interacting with a block with a GUI.
	interactMode = true
	#If interact mode fails with an exception, what level of logging should be performed?
	#Allowed Values: NONE, MESSAGE, STACK_TRACE
	interactExceptionReporting = "MESSAGE"

[Tools]
	#What should every level of the Overclock enchantment multiply the battery capacity of a tool by?
	#For example, 0.2 would be a 20% increase per enchantment level.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	overclockMultiplier = 0.2
	#How much knockback should each level of the Engineer's Fury enchantment add?
	#For example, 0.1 at Engineer's Fury X would add +1 total knockback.
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	engineersFuryMultiplier = 0.1

