
#Machines
[machines]
	#Specifies machine breakability while players are inside.
	# 'unbreakable' = Nobody can break while players are inside.
	# 'owner' = Only the owner can break while players are inside.
	# 'anyone' = Anyone can break while players are inside.
	#Allowed Values: UNBREAKABLE, OWNER, ANYONE
	breakHandling = "UNBREAKABLE"
	#The Y-dimension to spawn machine floors at.
	#Range: 10 ~ 200
	floor = 40
	#default: false
	allowOutside = false

[commands]

	[commands.permLevels]
		#Command level required for using the rebind and unbind commands.
		#Range: 0 ~ 4
		rebind = 0
		#Command level required for giving new machines to players.
		#Range: 0 ~ 4
		give = 0
		#Command level required for changing room spawn information.
		#Range: 0 ~ 4
		spawn = 2
		#Command level required for changing room upgrades.
		#Range: 0 ~ 4
		upgrades = 2

