
["Herb Jar Settings"]
	#Disabling allows jars to hold any item
	jars_only_hold_herbs = true

["Sage Burning Plate Settings"]
	#Range of the Sage Burning Plate, setting to 0 will disable completely
	spawn_disable_range = 30

["Sage Bundle Settings"]
	#Duration of how long each bundle will last while burning
	sage_bundle_duration_in_seconds = 3600

["Witch Hut Spacing"]
	#spacing between witch huts, lower both spacing and separation to increase spawn rates
	witch_hut_spacing = 66

["Witch Hut Separation"]
	#separation of the witch huts, lower both spacing and separation to increase spawn rates
	witch_hut_separation = 36

["Dark Coven Spacing"]
	#spacing between dark covens, lower both spacing and separation to increase spawn rates
	dark_coven_spacing = 58

["Dark Coven Separation"]
	#separation of the dark covens, lower both spacing and separation to increase spawn rates
	dark_coven_separation = 32

["Broom Brush Durability"]
	#100 durability will be about 16 minutes of flight time
	broom_brush_durability = 50

["Enhanced Broom Brush Durability"]
	#200 durability will be about 32 minutes of flight time
	enhanced_broom_brush_durability = 120

["Broom Netherite Tip Durability"]
	#1 second of active time per 1 durability
	broom_netherite_tip_durability = 120

["Broom Waterproof Tip Durability"]
	#1 second of active time per 1 durability
	broom_waterproof_tip_durability = 400

["Crow Pickpocket Cooldown"]
	#time (in ticks) for crow being able to pickpocket again (base 1 minute 30 seconds)
	crow_pickpocket_cooldown = 2200

