#Should vanished players be physically hidden from the world? This includes sound and particle suppression
hidePlayersFromWorld = true
#Should vanished players be hidden from player lists such as the /list command and the list in the Multiplayer screen?
hidePlayersFromPlayerLists = true
#Should vanished players not be targetable by normal players via command selectors (so non-admins cannot target vanished players with e.g. /msg)?
hidePlayersFromCommandSelectors = true
#When vanished players send a chat message, should the name of the player that sent the message be replaced with "vanished" (in gray color)?
hidePlayerNameInChat = false
#Should there be a (potential) fix for other mods uncovering the presence of vanished players? This may severely increase CPU usage and is thus not recommended
fixModCompat = false
#What op permission level should be the requirement for being able to execute /vanish?
#Range: 0 ~ 4
requiredPermissionLevel = 2

