
[general]
	#
	#Biome name where the Allay should spawn
	biome_name = "minecraft:forest"

	#Spawn rate settings
	[general.spawnrate]
		#Model type to choose from: 0 or 1
		#Range: 0 ~ 1
		type = 0

		#Allay
		[general.spawnrate.allay]
			#Spawn Chance
			#Range: > 0
			weight = 10
			#Monster Spawn Minimum Number
			#Range: > 0
			min = 0
			#Monster Spawn Maximum Number
			#Range: > 0
			max = 1

