
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 558084
	#The name of the modpack
	modpackName = "Another Quality Modpack 3"
	#The version of the modpack
	modpackVersion = "1.5"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

