
#Furnace Settings
[furnaces]
	# The capacity of the recipe cache, higher values use more memory.
	# Default: 10
	#Range: 1 ~ 100
	recipe_cache = 10

	[furnaces.copper_tier]
		# Number of ticks to complete one smelting operation.
		# 200 ticks is what a regular furnace takes.
		# Default: 120(Only work with Ultimate Furnaces addon)
		#Range: 2 ~ 72000
		speed = 180

	[furnaces.iron_tier]
		# Number of ticks to complete one smelting operation.
		# 200 ticks is what a regular furnace takes.
		# Default: 150
		#Range: 2 ~ 72000
		speed = 150

	[furnaces.gold_tier]
		# Number of ticks to complete one smelting operation.
		# 200 ticks is what a regular furnace takes.
		# Default: 100
		#Range: 2 ~ 72000
		speed = 100

	[furnaces.diamond_tier]
		# Number of ticks to complete one smelting operation.
		# 200 ticks is what a regular furnace takes.
		# Default: 80
		#Range: 2 ~ 72000
		speed = 80

	[furnaces.netherhot_tier]
		# Number of ticks to complete one smelting operation.
		# 200 ticks is what a regular furnace takes.
		# Default: 20
		#Range: 2 ~ 72000
		speed = 20

	[furnaces.extreme_tier]
		# Number of ticks to complete one smelting operation.
		# 200 ticks is what a regular furnace takes.
		# Default: 4
		#Range: 2 ~ 72000
		speed = 4

	[furnaces.ultimate_tier]
		# Number of ticks to complete one smelting operation.
		# 200 ticks is what a regular furnace takes.
		# Default: 1 (Only work with Ultimate Furnaces addon)
		#Range: 1 ~ 72000
		speed = 1

	[furnaces.furnace_xp_drop]
		# This value indicates when the furnace should 'overload' and spit out the xp stored. 
		# Default: 10, Recipes
		#Range: 1 ~ 500
		value = 10
		# This value indicates when the furnace should 'overload' and spit out the xp stored. 
		# Default: 100000, Single recipe uses
		#Range: 1 ~ 1000000
		value_two = 100000

	[furnaces.upgrade]
		# Value referring to the mod used for the xp fluid generated with the Xp Tank Upgrade. 
		# 0 = Mob Grinding Utils(Default) 
		# 1 = Industrial Foregoing 
		# 2 = Cyclic 
		# 3 = Reliquary
		#Range: 0 ~ 3
		xp_fluid_type = 0

#JEI Settings
[jei]

	[jei.jei]
		# Enable or disable the JeiPlugin of BetterFurnaces.
		enable_jei = true
		# Enable or disable the Catalysts in Jei for BetterFurnaces.
		enable_jei_catalysts = true
		# Enable or disable the Click Area inside the GUI in all of BetterFurnaces furnaces and forges.
		enable_jei_click_area = true

#Misc
[misc]

	[misc.misc]
		# Show furnace settings errors in chat, used for debugging
		errors = false

#Update Checker Settings
[updates]

	[updates.check_updates]
		# true = check for updates, false = don't check for updates.
		# Default: true.
		updates = true

