
[items]

	[items.oxygen_can]
		oxygenCapacity = 24000
		oxygenTransfer = 256

[machines]

	[machines.fuel_loader]
		fluidCapacity = 8000
		fluidTransfer = 256
		#blocks from FuelLoader to each direction
		workingRange = 2

	[machines.gravity_normalizer]
		#final energy usage = 'base' + range * 'perRange'
		energyUsingBase = 10
		energyUsingPerRange = 2

[compats]

	[compats.mekanism]

		[compats.mekanism.mekasuit_helmet]
			oxygenCapacity = 48000
			oxygenTransfer = 256

		[compats.mekanism.module_space_breathing_unit]
			#Fill amount of oxygen to helmet when player in water or rain
			#in rain, produce efficiency is half
			maxProduceRate = 4
			#Oxygen gas usage when provide Beyond Earth oxygen to player in space
			oxygenUsing = 1
			#Duration of provided oxygen (oxygen provide interval)
			oxygenDuration = 4
			#Energy usage when provide Beyond Earth oxygen to player in space
			energyUsing = 10

		[compats.mekanism.module_space_fire_proof_unit]
			#Energy usage when prevent fire every tick in Beyond Earth hot planets (e.g. Venus, Mercury)
			energyUsing = 10

		[compats.mekanism.module_venus_acid_proof_unit]
			#Energy usage when prevent acid rain damage every tick in Beyond Earth venus
			energyUsing = 10

		[compats.mekanism.module_space_gravity_normalizing_unit]
			#Energy usage when normalizing gravity every tick in Beyond Earth dimensions
			energyUsing = 10

		[compats.mekanism.module_gravitational_modulating_unit]
			#Can normalize gravity instead module_space_gravity_normalizing_unit
			normalizable = true
			#Energy usage when normalizing gravity every tick in Beyond Earth dimensions
			energyUsing = 10

