
["all mobs"]
	"Enable the fix for melee cooldowns for mobs?" = true
	#This determines the range a mob will detect other entities if they have the blindness potion, by default entities will only detect targets in a 10 block radius if they are blinded.
	#Range: -500.0 ~ 10000.0
	"Blindness range" = 0.1
	"Have all mobs attack villagers?" = false
	#Any mob id in this list will not attack villagers if the config option for that is on.
	"Mob BlackList" = []
	#Any mob id input in this list will be able to use the buckler
	"Mobs that can also use the buckler" = ["guardvillagers:guard"]

[buckler]
	"Have the explosion spawned while using the Bang! enchant destroy blocks?" = false
	"Have brutes spawn with bucklers?" = true
	#Range: > -2147483648
	"How long should the buckler's cooldown be in ticks?" = 240
	#Range: > -2147483648
	"How long should the buckler's charge move be in ticks?" = 15
	#Range: > -2147483648
	"How long should the buckler's charge move if you have the turning enchant be in ticks?" = 30

[pillager]
	"Have pillagers run while reloading?" = true
	"Have pillagers go closer to you if they have a multishot crossbow?" = true
	#Range: 0.0 ~ 900.0
	"Chance of a pillager patrol leader getting a spyglass" = 0.5

[animals]
	#Any mob id in this list will not attempt to find an area to stay in while it's raining or at night.
	"Animal BlackList" = ["minecraft:fox", "minecraft:wolf", "minecraft:turtle", "minecraft:polar_bear", "minecraft:axolotl"]
	#Any mob id in this list will not attempt to find an area to stay in while it's night.
	"Animal Night BlackList" = ["minecraft:cat"]
	#Any mob id in this list will not attempt to find an area to stay in while it's raining.
	"Animal Raining BlackList" = []
	"Animals seek shelter?" = true

	[animals.pigs]
		#Range: > -2147483648
		"What is the minimium amount of extra piglets that could be bred?" = 1
		#Range: > -2147483648
		"What is the maxmium amount of extra piglets that could be bred?" = 3

["polar bears"]
	"Have polar bears attack fish?" = true

[ocelots]
	"Have ocelots attack creepers? (Creepers won't attack back)" = true
	"Have ocelots attack parrots?" = true
	"Have ocelots attack phantoms?" = true

[sheep]
	"Have sheep run away from wolves?" = true

["snow golems"]
	#Freezing time can be added up by successive shots.
	"Allow snow balls to apply 5 seconds of freezing when they hit an entity?" = true

