
["after image"]
	"Render an after image while an entity is charging with a buckler?" = true
	#Keep in mind this won't affect their opacity due to technical reasons.
	"Render entity layers while rendering the after image?" = false

