#Enable fortune upgrades? (Can still be inserted into upgrade slots, but effects are disabled.)
enableFortuneUpgrade = true
#Enable efficiency upgrades? (Can still be inserted into upgrade slots, but effects are disabled.)
enableEfficiencyUpgrade = true
#Enable hopping upgrade? (Can still be inserted into upgrade slots, but effects are disabled.)
enableHoppingUpgrade = true
#Enable auto cutting upgrades? (Can still be inserted into upgrade slots, but effects are disabled.)
enableAutoCuttingUpgrade = true
#Show chance for drops in JEI
showChanceInJEI = true
#Summarize enchantment levels instead of using the highest level? (I.e. is '4 x Fortune III = Fortune XII'?)
sumEnchantmentLevels = true
#Drops: How many extra rolls per fortune enchantment level?
#Range: 0 ~ 64
extraRollsPerFortuneLevel = 1
#Drops: What is the bonus chance to get a successful drop per fortune enchantment level?
#Range: 0.0 ~ 1.0
extraChancePerFortuneLevel = 0.05
#Allow usage of bone meal on bonsai pots to boost their growth?
allowBonemeal = true
#How likely is it for bonemeal to succeed in boosting growth?
#Range: 0.0 ~ 1.0
bonemealSuccessChance = 0.35

