
[settings]
	#Configures if the block picking behavior should be inverted. When true then a normal middle-click will get the full chiseled block and a shift-middle-click gets the bit. If this is false then the behaviours are swapped.
	invert-pick-block-behaviour = false

	[settings.bit-bag]
		#Should the durability bar display the emptiness of the bag instead of the fullness?
		invert-durability-bar-indication = false

	[settings.chiseling-previews]
		#settings.chiseling-previews.renderer.comment
		renderer = "chiselsandbits:default"

		[settings.chiseling-previews.default]

			[settings.chiseling-previews.default.colors]
				#settings.chiseling-previews.default.colors.chiseling.comment
				chiseling = [0.85, 0.0, 0.0, 0.65]
				#settings.chiseling-previews.default.colors.placement.comment
				placement = [0.0, 0.85, 0.0, 0.65]

	[settings.selected-tool-mode-icons]
		#settings.selected-tool-mode-icons.renderer.comment
		renderer = "chiselsandbits:group"

	[settings.clipboard]
		#settings.clipboard.size.comment
		#Range: 0 ~ 64
		size = 64
		#mod.chiselsandbits.config.settings.clipboard.addbrokenblocks.comment
		addBrokenBlocks = true
		#mod.chiselsandbits.config.settings.clipboard.addpickedblocks.comment
		addPickedBlocks = true

[performance]

	[performance.caches]

		[performance.caches.sizes]
			#performance.caches.sizes.bit-storage-content-models.comment
			#Range: 0 ~ 9223372036854775807
			bit-storage-content-models = 100
			#performance.caches.sizes.block-models.comment
			#Range: 3500 ~ 20000
			block-models = 10000
			#performance.caches.sizes.block-faces.comment
			#Range: 350000 ~ 2000000
			block-faces = 1000000

	[performance.lighting]
		#Should C&B pull lighting values from model faces.
		extract-lighting-values-from-faces = true
		#Should C&B pull lighting values from blockstates.
		extract-lighting-values-from-blockstates = true

	[performance.model-building]
		#performance.model-building.thead-count.comment
		#Range: 1 ~ 8
		thead-count = 4

[gui]

	[gui.radial-menu]
		#Should the mouse indicator be rendered?
		display-mouse-indicator = false

