
#General settings
[General]
	#Default Howler Alarm Range
	#Range: > 0
	howlerAlarmRange = 64
	#Max Possible Howler Alarm Range
	#Range: > 0
	maxAlarmRange = 128
	#Allowed Alarms
	allowedAlarms = "default,sci-fi,siren"
	#Default Panel Refresh Period
	#Range: > 1
	infoPanelRefreshPeriod = 20
	#Default Range Trigger Refresh Period
	#Range: > 1
	rangeTriggerRefreshPeriod = 20
	#Load Custom Sounds
	useCustomSounds = false

