#Enable or disable a debug overlay that colors pixels by their normal
debugNormals = false
#Enable or disable the entire engine
#Allowed Values: OFF, BATCHING, INSTANCING
backend = "INSTANCING"

