
[General]
	#The capacity defines how many items a full FuelCanister can smelt (default =4096 = 8 Stacks Coal)
	#Range: 0 ~ 32767
	capacity = 4096

[Fuels]
	#A List of Fuels, that will be automatically consumed when right-clicking with the FuelCanister in Hand
	#Be careful about which items you put in here, as this can have unwanted consequences! (e.g. putting wood here uses up all your wood when using a FuelCanister)
	#Format of each List Entry: Recipe-Like Json. e.g. {item: "name"} or {tag: "TagName"}
	#For a simple item without metadata, just the item-id in the form mod_id:item_id is enough
	autoFuels = ["minecraft:coal", "minecraft:charcoal", "minecraft:coal_block", "gobber2:gobber2_foo", "gobber2:gobber2_foo_end", "gobber2:gobber2_foo_nether"]
	#If a player should be able to use any Item with a fuel value when using a crafting table to fill the FuelCanister, or only those defined by autoFuels
	craftAnyFuel = true

