
#Gobber Lucky Block Nether Generation
[gobber2_lucky_block_nether]
	#Maximal height for Gobber Lucky Block Nether pocket generation [0-255, default: 255]
	#Range: 0 ~ 255
	gobberLuckyBlockNetherMaxHeight = 255
	#Size of Gobber Lucky Block Nether pockets [3-100, default: 4]
	#Range: 3 ~ 100
	gobberLuckyBlockNetherSize = 4
	#Minimal height for Gobber Lucky Block Nether pocket generation, [0-255, default: 1]
	#Range: 0 ~ 255
	gobberLuckyBlockNetherMinHeight = 1
	#Chances of Gobber Lucky Block Nether pocket being generated [0-30, default: 20]
	#Range: 0 ~ 30
	gobberLuckyBlockNetherChance = 10
	#Generate Gobber Lucky Block Nether in the world [true / false]
	gobberLuckyBlockNetherGeneration = true

#Nether Gobber Food Values
[nether_gobber_foods]
	#Nether Gooey beef hunger value [default: 12]
	#Range: 0 ~ 25
	netherGooeyBeefHunger = 11
	#Nether Goo hunger value [default: 9]
	#Range: 0 ~ 25
	netherGooHunger = 9
	#Nether Gooey bread saturation value [default: 1.0]
	#Range: 0.0 ~ 5.0
	netherGooeyBreadSaturation = 1.0
	#Nether Gooey beef saturation value [default: 1.2]
	#Range: 0.0 ~ 5.0
	netherGooeyBeefSaturation = 1.1
	#Nether Gooey apple hunger value [default: 10]
	#Range: 0 ~ 25
	netherGooeyAppleHunger = 10
	#Nether Gooey beefstew saturation value [default: 1.5]
	#Range: 0.0 ~ 5.0
	netherGooeyBeefstewSaturation = 1.2
	#Nether Goo saturation value [default: 0.9]
	#Range: 0.0 ~ 5.0
	netherGooSaturation = 0.9
	#Nether Gooey apple saturation value [default: 1.0]
	#Range: 0.0 ~ 5.0
	netherGooeyAppleSaturation = 1.0
	#Nether Gooey bread hunger value [default: 10]
	#Range: 0 ~ 25
	netherGooeyBreadHunger = 9
	#Nether Gooey beefstew hunger value [default: 14]
	#Range: 0 ~ 25
	netherGooeyBeefstewHunger = 12

#Item Cooldown Settings
[item_cooldown_settings]
	#Number of ticks duration for the Ring of Husbandry cooldown [default: 2400]
	#Range: 0 ~ 9600
	ringHusbandryCooldown = 3200
	#Number of ticks duration for the Staff of the Sniper cooldown [default: 60]
	#Range: 0 ~ 3600
	staffSniperCooldown = 120
	#Number of ticks duration for the Ring of the Explorer cooldown [default: 480]
	#Range: 0 ~ 3600
	ringExplorerCooldown = 1200
	#Number of ticks duration for the Ring of Above cooldown [default: 80]
	#Range: 0 ~ 3600
	ringAboveCooldown = 140
	#Number of ticks duration for the Sword of the Sniper cooldown [default: 60]
	#Range: 0 ~ 3600
	swordSniperCooldown = 120
	#Number of ticks duration for the Ring of the Miner cooldown [default: 80]
	#Range: 0 ~ 3600
	ringMinerCooldown = 200
	#Number of ticks duration for the Ring of Blink cooldown [default: 60]
	#Range: 0 ~ 3600
	ringBlinkCooldown = 90

#Medallion of Experience Settings
[medallion_exp_settings]
	#Medallion of Experience multiplier for extra mob loot [default: 20]
	#Range: 5 ~ 100
	medallionExpLoot = 7
	#Medallion of Experience multiplier for extra XP orbs [default: 5]
	#Range: 0 ~ 20
	medallionExpOrbs = 5

#Misc Ring/staff Settings
[misc_ring_staff_settings]
	#Ring of Attraction - Items are instantly placed in player inventory  [true / false, default: false]
	ringAttractionMode = false
	#Ring of Dismissal - Sets the horizontal velocity [default: 0.2]
	#Range: 0.0 ~ 15.0
	ringDismissalVelocity = 0.2
	#Uses a delayed break mode to reduce stutter and potential lag on Ring of Miner and Ring of Lumberjack [true / false, default: true]
	delayedBreakMode = true
	#Ring of Repair - Delay time between repair ticks [default: 120]
	#Range: 20 ~ 600
	ringRepairDelay = 400
	#Enable a single use of the Ring of Teleport [true / false, default: false]
	limitedUseRingTeleport = false
	#Reverse the drop/no drops feature on Ring of Miner [true / false, default: false]
	reverseRingMiner = false
	#Ring of Acceleration - amount of velocity applied [default: 0.18]
	#Range: 0.0 ~ 0.3
	ringAccelerationVelocity = 0.14
	#Ring of Dismissal - Sets the horizontal range to detect mobs [default: 8.0]
	#Range: 0.0 ~ 16.0
	ringDismissalLift = 7.0
	#Ring of Attraction - Distance coal blocks magnet effect [default: 5]
	#Range: 0 ~ 15
	ringAttractionBlocking = 4

#Armor Health Perks Settings
[armor_health_perk_settings]
	#Enable/disable Gobber Armor No Fall Damage [true / false, default: true]
	gobberArmorNoFallDamage = false
	#Enable/disable Gobber Dragon Armor health perks [true / false, default: true]
	gobberDragonArmorHealthPerks = false
	#Enable/disable Gobber Nether Armor health perks [true / false, default: true]
	gobberNetherArmorHealthPerks = false
	#Enable/disable Gobber Armor fire protection [true / false, default: true]
	gobberArmorFireProtection = false
	#Enable/disable Gobber Armor health perks [true / false, default: true]
	gobberArmorHealthPerks = false
	#Enable/disable Gobber End Armor health perks [true / false, default: true]
	gobberEndArmorHealthPerks = false
	#Enable/disable Gobber Armor water breathing [true / false, default: true]
	gobberArmorWaterBreathing = false
	#Enable/disable Gobber Armor auto feeding [true / false, default: true]
	gobberArmorAutofeed = false
	#Enable/disable Gobber Nether Armor auto feeding [true / false, default: true]
	gobberNetherArmorAutofeed = false
	#Enable/disable Gobber End Armor auto feeding [true / false, default: true]
	gobberEndArmorAutofeed = false
	#Enable/disable Gobber Dragon Armor auto feeding [true / false, default: true]
	gobberDragonArmorAutofeed = false
	#Enable/disable Gobber Dragon Armor flight [true / false, default: true]
	gobberDragonArmorFlight = false
	#Enable/disable Gobber Nether Armor yellow hearts perks [true / false, default: true]
	gobberNetherArmorYellowHeartsPerks = false
	#Enable/disable Gobber End Armor yellow hearts perks [true / false, default: true]
	gobberEndArmorYellowHeartsPerks = false
	#Enable/disable Gobber Dragon Armor yellow hearts perks [true / false, default: true]
	gobberDragonArmorYellowHeartsPerks = true

#Auto Replanting Settings
[replanting_settings]
	#Should the Staff of the Farmer auto-replant? [true / false, default: true]
	StaffFarmerReplant = true
	#Should the Staff of Harvest auto-replant? [true / false, default: true]
	StaffHarvestReplant = false

#Armor Hunger/Saturation Settings
[armor_health_settings]
	#Amount of hunger points to restore per interval [default: 1]
	#Range: 0 ~ 10
	gobberArmorHunger = 0
	#Amount of saturation points to restore per interval [default: 0.10]
	#Range: 0.0 ~ 10.0
	gobberEndArmorSaturation = 0
	#Amount of hunger points to restore per interval [default: 1]
	#Range: 0 ~ 10
	gobberNetherArmorHunger = 0
	#Amount of saturation points to restore per interval [default: 0.02]
	#Range: 0.0 ~ 10.0
	gobberArmorSaturation = 0
	#Amount of saturation points to restore per interval [default: 0.15]
	#Range: 0.0 ~ 10.0
	gobberDragonArmorSaturation = 0
	#Amount of hunger points to restore per interval [default: 1]
	#Range: 0 ~ 10
	gobberEndArmorHunger = 0
	#Amount of hunger points to restore per interval [default: 1]
	#Range: 0 ~ 10
	gobberDragonArmorHunger = 0
	#Amount of saturation points to restore per interval [default: 0.05]
	#Range: 0.0 ~ 10.0
	gobberNetherArmorSaturation = 0

#Gobber Food Values
[gobber_foods]
	#Gooey beef saturation value [default: 0.9]
	#Range: 0.0 ~ 5.0
	gooeyBeefSaturation = 0.9
	#Gooey beef hunger value [default: 9]
	#Range: 0 ~ 25
	gooeyBeefHunger = 9
	#Gooey bread hunger value [default: 8]
	#Range: 0 ~ 25
	gooeyBreadHunger = 8
	#Goo saturation value [default: 0.7]
	#Range: 0.0 ~ 5.0
	gooSaturation = 0.7
	#Gooey apple saturation value [default: 0.8]
	#Range: 0.0 ~ 5.0
	gooeyAppleSaturation = 0.8
	#Gooey bread saturation value [default: 0.8]
	#Range: 0.0 ~ 5.0
	gooeyBreadSaturation = 0.8
	#Goo hunger value [default: 7]
	#Range: 0 ~ 25
	gooHunger = 7
	#Gooey beefstew hunger value [default: 10]
	#Range: 0 ~ 25
	gooeyBeefstewHunger = 10
	#Gooey apple hunger value [default: 8]
	#Range: 0 ~ 25
	gooeyAppleHunger = 8
	#Gooey beefstew saturation value [default: 1.0]
	#Range: 0.0 ~ 5.0
	gooeyBeefstewSaturation = 1.0

#Dragon Egg With Every Kill
[dragon_egg_kill]
	#Enable Dragon Egg drops on every kill [true / false, default: false]
	enableDragonEggEveryKill = false

#Gobber Armor Material Values
[gobber_armor_material]
	#Gobber armor enchantability [default: 25]
	#Range: 1 ~ 50
	gobberArmorEnchantability = 15
	#Gobber armor durability multiplier [default: 71]
	#Range: 1 ~ 200
	gobberArmorDurabilityMultiplier = 68
	#Gobber armor toughness [default: 2.5]
	#Range: 0.0 ~ 5.0
	gobberArmorToughness = 2.25
	#Gobber armor knockback [default: 0.1]
	#Range: 0.0 ~ 5.0
	gobberArmorKnockback = 0.1
	#Gobber armor head protection [default: 6]
	#Range: 1 ~ 20
	gobberHeadProtection = 5
	#Gobber armor chest protection [default: 11]
	#Range: 1 ~ 20
	gobberChestProtection = 10
	#Gobber armor leggings protection [default: 9]
	#Range: 1 ~ 20
	gobberLeggingsProtection = 6
	#Gobber armor boots protection [default: 6]
	#Range: 1 ~ 20
	gobberBootsProtection = 4

#Gobber Lucky Block and Deepslate Generation
[gobber2_lucky_block]
	#Size of Gobber Lucky Block pockets [3-100, default: 4]
	#Range: 3 ~ 100
	gobberLuckyBlockSize = 3
	#Chances of Gobber Lucky Block pocket being generated [0-30, default: 20]
	#Range: 0 ~ 30
	gobberLuckyBlockChance = 9
	#Minimal height for Gobber Lucky Block pocket generation, [-64-384, default: -64]
	#Range: -64 ~ 384
	gobberLuckyBlockMinHeight = 1
	#Maximal height for Gobber Lucky Block pocket generation [-64-384, default: 255]
	#Range: -64 ~ 384
	gobberLuckyBlockMaxHeight = 255
	#Generate Gobber Lucky Block in the world [true / false]
	gobberLuckyBlockGeneration = true

#Nether Gobber Tool Material Values
[nether_gobber_tool_material]
	#Nether Gobber tool attack damage [default: 9.0]
	#Range: 1.0 ~ 100.0
	netherGobberToolsDamage = 6.0
	#Nether Gobber tool durability [default: 5200]
	#Range: 0 ~ 9000
	netherGobberToolsDurability = 5200
	#Nether Gobber tool mining speed [default: 12.0]
	#Range: 1.0 ~ 25.0
	netherGobberToolsSpeed = 11.0
	#Nether Gobber tool enchantability [default: 25]
	#Range: 1 ~ 50
	netherGobberToolsEnchantability = 17

#End Gobber Armor Material Values
[end_gobber_armor_material]
	#End Gobber armor enchantability [default: 30]
	#Range: 1 ~ 50
	endGobberArmorEnchantability = 20
	#End Gobber armor toughness [default: 3.0]
	#Range: 0.0 ~ 5.0
	endGobberArmorToughness = 3.5
	#End Gobber armor knockback [default: 0.2]
	#Range: 0.0 ~ 5.0
	endGobberArmorKnockback = 0.15
	#End Gobber armor durability multiplier [default: 100]
	#Range: 1 ~ 200
	endGobberArmorDurabilityMultiplier = 100
	#Should Armor be unbreakable when crafted? [true / false, default: true]
	endGobberArmorUnbreakable = true
	#End armor head protection [default: 8]
	#Range: 1 ~ 20
	endHeadProtection = 8
	#End armor chest protection [default: 13]
	#Range: 1 ~ 20
	endChestProtection = 12
	#End armor leggings protection [default: 11]
	#Range: 1 ~ 20
	endLeggingsProtection = 10
	#End armor boots protection [default: 8]
	#Range: 1 ~ 20
	endBootsProtection = 8

#Gobber and Deepslate Ore Generation
[gobber2_ore]
	#Size of Gobber Ore pockets [3-100, default: 4]
	#Range: 3 ~ 100
	gobberOreSize = 3
	#Chances of Gobber Ore pocket being generated [0-30, default: 15]
	#Range: 0 ~ 30
	gobberOreChance = 9
	#Minimal height for Gobber Ore pocket generation, [-64-384, default: -64]
	#Range: -64 ~ 384
	gobberOreMinHeight = -44
	#Maximal height for Gobber Ore pocket generation [-64-384, default: 30]
	#Range: -64 ~ 384
	gobberOreMaxHeight = 40
	#Generate Gobber Ore in the world [true / false]
	gobberOreGeneration = true

#Gobber End Ore Generation
[gobber2_ore_end]
	#Minimal height for Gobber End Ore pocket generation, [0-255, default: 40]
	#Range: 0 ~ 255
	gobberOreEndMinHeight = 10
	#Size of Gobber End Ore pockets [0-100, default: 9]
	#Range: 0 ~ 100
	gobberOreEndSize = 4
	#Maximal height for Gobber End Ore pocket generation [0-255, default: 255]
	#Range: 0 ~ 255
	gobberOreEndMaxHeight = 90
	#Chances of Gobber End Ore pocket being generated [0-30, default: 15]
	#Range: 0 ~ 30
	gobberOreEndChance = 6
	#Generate Gobber End Ore in the world [true / false]
	gobberOreEndGeneration = true

#Enable Dragon Armor Void Protect - immune to /kill command
[dragon_armor_void]
	#Enable Dragon Armor Void Protection [true / false, default: false]
	enableDragonArmorVoidProtection = true

#Nether Gobber Armor Material Values
[nether_gobber_armor_material]
	#Nether Gobber armor knockback [default: 0.1]
	#Range: 0.0 ~ 5.0
	netherGobberArmorKnockback = 0.13
	#Nether Gobber armor toughness [default: 2.75]
	#Range: 0.0 ~ 5.0
	netherGobberArmorToughness = 2.75
	#Nether Gobber armor enchantability [default: 30]
	#Range: 1 ~ 50
	netherGobberArmorEnchantability = 15
	#Nether Gobber armor durability multiplier [default: 83]
	#Range: 1 ~ 200
	netherGobberArmorDurabilityMultiplier = 83
	#Nether armor head protection [default: 7]
	#Range: 1 ~ 20
	netherHeadProtection = 6
	#Nether armor chest protection [default: 12]
	#Range: 1 ~ 20
	netherChestProtection = 11
	#Nether armor leggings protection [default: 10]
	#Range: 1 ~ 20
	netherLeggingsProtection = 7
	#Nether armor boots protection [default: 7]
	#Range: 1 ~ 20
	netherBootsProtection = 5

#Ring of the Explorer Settings
[ring_explorer_settings]
	#Ring of Explorer - Max distance from world spawn to begin searching for a spot [default: 6000]
	#Range: 0 ~ 250000
	ringExplorerMax = 6000
	#Ring of Explorer - Min distance from world spawn to begin searching for a spot [default: 500]
	#Range: 0 ~ 100000
	ringExplorerMin = 500

#Gobber Tool Material Values
[gobber_tool_material]
	#Gobber tool enchantability [default: 20]
	#Range: 1 ~ 50
	gobberToolsEnchantability = 10
	#Gobber tool durability [default: 3800]
	#Range: 0 ~ 9000
	gobberToolsDurability = 3800
	#Gobber tool mining speed [default: 9.0]
	#Range: 1.0 ~ 25.0
	gobberToolsSpeed = 9.0
	#Gobber tool attack damage [default: 9.0]
	#Range: 1.0 ~ 100.0
	gobberToolsDamage = 6.0

#End Gobber Tool Material Values
[end_gobber_tool_material]
	#End Gobber tool enchantability [default: 30]
	#Range: 1 ~ 50
	endGobberToolsEnchantability = 15
	#Should Tools be unbreakable when crafted? [true / false, default: true]
	endGobberToolsUnbreakable = true
	#End Gobber tool durability [default: 8000]
	#Range: 0 ~ 9000
	endGobberToolsDurability = 8000
	#End Gobber tool attack damage [default: 9.0]
	#Range: 1.0 ~ 100.0
	endGobberToolsDamage = 6.0
	#End Gobber tool mining speed [default: 14.0]
	#Range: 1.0 ~ 25.0
	endGobberToolsSpeed = 12.0

#Ring/Staff of Farmer Settings
[farmer_settings]
	#Ring of the Farmer base tick delay [default: 20]
	#Range: 10 ~ 120
	ringFarmerTickDelay = 60
	#Staff of the Farmer radius from player [default: 10]
	#Range: 2 ~ 20
	staffFarmerRadius = 8
	#Staff of the Farmer base tick delay [default: 20]
	#Range: 10 ~ 120
	staffFarmerTickDelay = 40
	#Ring of the Farmer radius from player [default: 10]
	#Range: 2 ~ 20
	ringFarmerRadius = 6

#Dragon Star Special
[dragonStar_special]
	#Enable Dragon Star Offhannd Function [true / false, default: true]
	enableDragonStarOffhand = false

#Gobber Nether Ore Generation
[gobber2_ore_nether]
	#Maximal height for Gobber Nether Ore pocket generation [0-255, default: 255]
	#Range: 0 ~ 255
	gobberOreNetherMaxHeight = 100
	#Minimal height for Gobber Nether Ore pocket generation, [0-255, default: 5]
	#Range: 0 ~ 255
	gobberOreNetherMinHeight = 40
	#Size of Gobber Nether Ore pockets [3-100, default: 3]
	#Range: 3 ~ 100
	gobberOreNetherSize = 4
	#Chances of Gobber Nether Ore pocket being generated [0-30, default: 15]
	#Range: 0 ~ 30
	gobberOreNetherChance = 8
	#Generate Gobber Nether Ore in the world [true / false]
	gobberOreNetherGeneration = true

#Dragon Armor Material Values
[dragon_armor_material]
	#Should Armor be unbreakable when crafted? [true / false, default: true]
	dragonArmorUnbreakable = true
	#Dragon armor enchantability [default: 30]
	#Range: 1 ~ 50
	dragonArmorEnchantability = 20
	#Dragon armor toughness [default: 3.0]
	#Range: 0.0 ~ 5.0
	dragonArmorToughness = 3.75
	#Dragon armor knockback [default: 0.3]
	#Range: 0.0 ~ 5.0
	dragonArmorKnockback = 0.175
	#Dragon armor durability multiplier [default: 100]
	#Range: 1 ~ 200
	dragonArmorDurabilityMultiplier = 100
	#Dragon armor head protection [default: 8]
	#Range: 1 ~ 20
	dragonHeadProtection = 8
	#Dragon armor chest protection [default: 13]
	#Range: 1 ~ 20
	dragonChestProtection = 13
	#Dragon armor leggings protection [default: 11]
	#Range: 1 ~ 20
	dragonLeggingsProtection = 11
	#Dragon armor boots protection [default: 8]
	#Range: 1 ~ 20
	dragonBootsProtection = 8

