
# Welcome to The Graveyard Config!
#
# Structures:
# Configure separation (Minimum distance between two structures of this type in chunks. Must be less than spacing).
# Configure spacing (Average distance between two structure placement attempts of this type in chunks).
# Configure whitelist: use "#biomeCategory" for biome categories and "minecraft:biome" for biomes (mod identifier + ":" + biome name).
# Configure blacklist: use "#biomeCategory" for biome categories and "minecraft:biome" for biomes (mod identifier + ":" + biome name).
# Configure mod whitelist: use "#modid" to whitelist the biomes of the specified mod for structures to spawn in (examples: #minecraft, #graveyard, #graveyard_biomes, #terralith, #byg, #bop).
# Valid vanilla biome categories are: #taiga, #extreme_hills, #jungle, #mesa, #plains, #savanna, #icy, #beach, #forest, #desert, #swamp, #mushroom, #underground, #mountain.
# A full list of all the biomes can be found here https:minecraft.fandom.com/wiki/Biome#Biome_IDs.
#
# Mobs:
# Configure spawning weight and group size of the spawn.
# Configure if mobs burn in sunlight and/or if mobs are affected by the wither effect.
# Configure whitelist: use "#biomeCategory" for biome categories and "minecraft:biome" for biomes (mod identifier + ":" + biome name).
# Configure blacklist: use "#biomeCategory" for biome categories and "minecraft:biome" for biomes (mod identifier + ":" + biome name).
# Configure mod whitelist: use "#modid" to whitelist the biomes of the specified mod for structures to spawn in (examples: #minecraft, #graveyard, #graveyard_biomes, #terralith, #byg, #bop).
#
# Additional:
# Configure graveyard fog particles rising from moss and set the chance of spawning them (higher numbers = lower chance of spawning).
# Configure if hordes of graveyard mobs can spawn and set their size and frequency.
# Configure if urns have a double chest inventory.
#
["The Graveyard - Structures Config"]

	["The Graveyard - Structures Config".small_graveyard]
		#Range: 0 ~ 200
		spacing = 62
		#Range: 0 ~ 200
		separation = 32
		canGenerate = true
		#Range: 0 ~ 10000000000
		salt = 240451934
		whitelist = ["#plains"]
		blacklist = []
		modWhitelist = ["#minecraft", "#terralith", "#byg"]
		canSpawnMobs = false

	["The Graveyard - Structures Config".small_desert_graveyard]
		#Range: 0 ~ 200
		spacing = 40
		#Range: 0 ~ 200
		separation = 22
		canGenerate = true
		#Range: 0 ~ 10000000000
		salt = 598017285
		whitelist = ["#desert"]
		blacklist = []
		modWhitelist = ["#minecraft", "#terralith", "#byg"]
		canSpawnMobs = false

	["The Graveyard - Structures Config".small_grave]
		#Range: 0 ~ 200
		spacing = 40
		#Range: 0 ~ 200
		separation = 18
		canGenerate = true
		#Range: 0 ~ 10000000000
		salt = 661903018
		whitelist = ["#taiga", "#forest", "#plains"]
		blacklist = []
		modWhitelist = ["#minecraft", "#graveyard_biomes", "#terralith", "#byg"]
		canSpawnMobs = false

	["The Graveyard - Structures Config".small_desert_grave]
		#Range: 0 ~ 200
		spacing = 32
		#Range: 0 ~ 200
		separation = 16
		canGenerate = true
		#Range: 0 ~ 10000000000
		salt = 681236914
		whitelist = ["#desert"]
		blacklist = []
		modWhitelist = ["#minecraft", "#terralith", "#byg"]
		canSpawnMobs = false

	["The Graveyard - Structures Config".small_savanna_grave]
		#Range: 0 ~ 200
		spacing = 40
		#Range: 0 ~ 200
		separation = 18
		canGenerate = true
		#Range: 0 ~ 10000000000
		salt = 709787761
		whitelist = ["#mesa", "#savanna"]
		blacklist = []
		modWhitelist = ["#minecraft", "#terralith", "#byg"]
		canSpawnMobs = false

	["The Graveyard - Structures Config".small_mountain_grave]
		#Range: 0 ~ 200
		spacing = 40
		#Range: 0 ~ 200
		separation = 18
		canGenerate = true
		#Range: 0 ~ 10000000000
		salt = 725689810
		whitelist = ["#mountain", "#extreme_hills"]
		blacklist = []
		modWhitelist = ["#minecraft", "#terralith", "#byg"]
		canSpawnMobs = false

	["The Graveyard - Structures Config".mushroom_grave]
		#Range: 0 ~ 200
		spacing = 76
		#Range: 0 ~ 200
		separation = 42
		canGenerate = true
		#Range: 0 ~ 10000000000
		salt = 379123039
		whitelist = ["#mushroom", "#jungle", "#swamp"]
		blacklist = []
		modWhitelist = ["#minecraft", "#terralith", "#byg"]
		canSpawnMobs = false

	["The Graveyard - Structures Config".memorial_tree]
		#Range: 0 ~ 200
		spacing = 68
		#Range: 0 ~ 200
		separation = 32
		canGenerate = true
		#Range: 0 ~ 10000000000
		salt = 529239621
		whitelist = ["minecraft:old_growth_birch_forest", "minecraft:birch_forest", "terralith:birch_taiga"]
		blacklist = []
		modWhitelist = ["#minecraft", "#terralith", "#byg"]
		canSpawnMobs = false

	["The Graveyard - Structures Config".medium_graveyard]
		#Range: 0 ~ 200
		spacing = 91
		#Range: 0 ~ 200
		separation = 51
		canGenerate = true
		#Range: 0 ~ 10000000000
		salt = 1690192399
		whitelist = ["#forest"]
		blacklist = ["minecraft:dark_forest", "minecraft:birch_forest", "minecraft:old_growth_birch_forest", "graveyard_biomes:haunted_lakes", "graveyard_biomes:haunted_forest"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]
		canSpawnMobs = true

	["The Graveyard - Structures Config".large_graveyard]
		#Range: 0 ~ 200
		spacing = 160
		#Range: 0 ~ 200
		separation = 100
		canGenerate = true
		#Range: 0 ~ 10000000000
		salt = 304812394
		whitelist = ["#forest", "#taiga"]
		blacklist = ["minecraft:forest", "minecraft:flower_forest", "minecraft:birch_forest", "minecraft:old_growth_birch_forest", "minecraft:windswept_forest", "graveyard_biomes:eroded_haunted_forest", "graveyard_biomes:haunted_lakes"]
		modWhitelist = ["#minecraft", "#graveyard_biomes", "#byg"]
		canSpawnMobs = true

	["The Graveyard - Structures Config".haunted_house]
		#Range: 0 ~ 200
		spacing = 90
		#Range: 0 ~ 200
		separation = 30
		canGenerate = true
		#Range: 0 ~ 10000000000
		salt = 451235912
		whitelist = ["#forest", "#swamp"]
		blacklist = ["minecraft:forest", "minecraft:flower_forest", "minecraft:birch_forest", "minecraft:old_growth_birch_forest", "minecraft:windswept_forest", "graveyard_biomes:haunted_forest"]
		modWhitelist = ["#minecraft", "#graveyard_biomes", "#byg"]
		canSpawnMobs = false

	["The Graveyard - Structures Config".giant_mushroom]
		canGenerate = true
		#Range: 0 ~ 200
		spacing = 77
		#Range: 0 ~ 200
		separation = 55
		#Range: 0 ~ 10000000000
		salt = 365012356
		whitelist = ["#mushroom"]
		blacklist = []
		modWhitelist = ["#minecraft", "#terralith"]
		canSpawnMobs = false

	["The Graveyard - Structures Config".altar]
		canGenerate = true
		#Range: 0 ~ 200
		spacing = 90
		#Range: 0 ~ 200
		separation = 40
		#Range: 0 ~ 10000000000
		salt = 1093123913
		whitelist = ["minecraft:snowy_plains"]
		blacklist = []
		modWhitelist = ["#minecraft", "#terralith"]
		canSpawnMobs = false

	["The Graveyard - Structures Config".crypt]
		canGenerate = true
		#Range: 0 ~ 200
		spacing = 50
		#Range: 0 ~ 200
		separation = 30
		#Range: 0 ~ 10000000000
		salt = 893183913
		whitelist = ["#underground"]
		blacklist = []
		modWhitelist = ["#minecraft", "#terralith"]
		canSpawnMobs = false

["The Graveyard - Mob Spawning Config"]

	["The Graveyard - Mob Spawning Config".ghoul]
		enabled = true
		#Range: 0 ~ 100
		weight = 12
		#Range: 1 ~ 100
		minGroupSizeGhoul = 2
		#Range: 1 ~ 100
		maxGroupSizeGhoul = 3
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["#taiga", "#extreme_hills", "#jungle", "#mesa", "#plains", "#savanna", "#icy", "#beach", "#forest", "#desert", "#swamp", "#underground", "#mountain"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes", "#byg"]

	["The Graveyard - Mob Spawning Config".revenant]
		enabled = true
		#Range: 0 ~ 100
		weight = 12
		#Range: 1 ~ 100
		minGroupSizeRevenant = 2
		#Range: 1 ~ 100
		maxGroupSizeRevenant = 3
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["#taiga", "#extreme_hills", "#jungle", "#mesa", "#plains", "#savanna", "#icy", "#beach", "#forest", "#desert", "#swamp", "#underground", "#mountain"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes", "#byg"]

	["The Graveyard - Mob Spawning Config".reaper]
		enabled = true
		#Range: 0 ~ 100
		weight = 5
		#Range: 1 ~ 100
		minGroupSizeReaper = 1
		#Range: 1 ~ 100
		maxGroupSizeGhoul = 2
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["graveyard_biomes:eroded_haunted_forest"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes", "#byg"]

	["The Graveyard - Mob Spawning Config".nightmare]
		enabled = true
		#Range: 0 ~ 100
		weight = 5
		#Range: 1 ~ 100
		minGroupSizeNightmare = 1
		#Range: 1 ~ 100
		maxGroupSizeNightmare = 1
		canBurnInSunlight = false
		canBeWithered = false
		whitelist = ["#taiga", "#extreme_hills", "#jungle", "#mesa", "#plains", "#savanna", "#icy", "#beach", "#forest", "#desert", "#swamp", "#underground", "#mountain"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes", "#byg"]

	["The Graveyard - Mob Spawning Config".skeleton_creeper]
		enabled = true
		#Range: 0 ~ 100
		weight = 8
		#Range: 1 ~ 100
		minGroupSizeSkeletonCreeper = 1
		#Range: 1 ~ 100
		maxGroupSizeSkeletonCreeper = 2
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["#taiga", "#extreme_hills", "#jungle", "#mesa", "#plains", "#savanna", "#icy", "#beach", "#forest", "#desert", "#swamp", "#underground", "#mountain"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes", "#byg"]

	["The Graveyard - Mob Spawning Config".acolyte]
		enabled = true
		#Range: 0 ~ 100
		weight = 7
		#Range: 1 ~ 100
		minGroupSizeAcolyte = 1
		#Range: 1 ~ 100
		maxGroupSizeAcolyte = 2
		canBurnInSunlight = false
		canBeWithered = false
		whitelist = ["#taiga", "#extreme_hills", "#jungle", "#mesa", "#plains", "#savanna", "#icy", "#beach", "#forest", "#desert", "#swamp", "#underground", "#mountain"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes", "#byg"]

	["The Graveyard - Mob Spawning Config".wraith]
		enabled = false
		#Range: 0 ~ 100
		weight = 0
		#Range: 1 ~ 100
		minGroupSizeWraith = 2
		#Range: 1 ~ 100
		maxGroupSizeWraith = 3
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["#taiga", "#extreme_hills", "#jungle", "#mesa", "#plains", "#savanna", "#icy", "#beach", "#forest", "#desert", "#swamp", "#underground", "#mountain"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

	["The Graveyard - Mob Spawning Config".corruptedPillager]
		enabled = false
		#Range: 0 ~ 100
		weight = 0
		#Range: 1 ~ 100
		minGroupSizeCorruptedPillager = 2
		#Range: 1 ~ 100
		maxGroupSizeCorruptedPillager = 3
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["#taiga", "#extreme_hills", "#jungle", "#mesa", "#plains", "#savanna", "#icy", "#beach", "#forest", "#desert", "#swamp", "#underground", "#mountain"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

	["The Graveyard - Mob Spawning Config".corruptedVindicator]
		enabled = false
		#Range: 0 ~ 100
		weight = 0
		#Range: 1 ~ 100
		minGroupSizeCorruptedVindicator = 2
		#Range: 1 ~ 100
		maxGroupSizeCorruptedVindicator = 3
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["#taiga", "#extreme_hills", "#jungle", "#mesa", "#plains", "#savanna", "#icy", "#beach", "#forest", "#desert", "#swamp", "#underground", "#mountain"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

["The Graveyard - Horde Config"]

	["The Graveyard - Horde Config".horde]
		generate = true
		#Range: 1 ~ 1000000
		ticksUntilSpawnHorde = 66000
		#Range: 0 ~ 1000
		mobSpawnAttempts = 20
		#Range: 1 ~ 1000000
		additionalRandomizedTicks = 1800

["The Graveyard - Particle Config"]

	["The Graveyard - Particle Config".particle]
		generate = true
		#Range: 1 ~ 500
		frequency = 20

["The Graveyard - Additional Config"]

	["The Graveyard - Additional Config".urn]
		urnHasDoubleInventory = true

	["The Graveyard - Additional Config".spawner]
		disableWitherSkeletonSpawner = true

	["The Graveyard - Additional Config".terrain]
		#Range: 1 ~ 100
		maxTerrainHeightDifference = 6

