
[health]
	#Show vanilla hearts
	healthVanilla = true
	#Colors for every 10 hearts (not counting the default red)
	#All values are written as hexadecimal RGB color in '#RRGGBB' format
	healthColors = ["#F06E14", "#F5DC23", "#2DB928", "#1EAFBE", "#7346E1", "#FA7DEB", "#EB375A", "#FF8278", "#AAFFFA", "#EBEBFF"]
	#Two alternating colors when poisoned
	#There can be one color in case vanilla poisoned heart is wanted
	healthPoisonColors = ["#739B00"]
	#Two alternating colors when withered
	#There can be one color in case vanilla withered heart is wanted
	healthWitherColors = ["#0F0F0F"]
	#Two alternating colors when frozen
	#There can be one color in case vanilla frozen heart is wanted
	healthFrozenColors = ["#3E70E6"]

[absorption]
	#Show vanilla hearts
	absorptionVanilla = true
	#Colors for every 10 hearts (not counting the default yellow)
	#All values are written as hexadecimal RGB color in '#RRGGBB' format
	absorptionColors = ["#E1FA9B", "#A0FFAF", "#AAFFFA", "#AACDFF", "#D7B4FF", "#FAA5FF", "#FFB4B4", "#FFAA7D", "#D7F0FF", "#EBFFFA"]
	#Two alternating colors when poisoned
	absorptionPoisonColors = ["#BFF230", "#7AA15A"]
	#Two alternating colors when withered
	absorptionWitherColors = ["#787061", "#73625C"]
	#Two alternating colors when freezing
	absorptionFrozenColors = ["#90D136", "#36D183"]

	[absorption.advanced]
		#Display absorption in the same row as health
		#Absorption is render after and over health depending on the mode
		absorptionOverHealth = false
		#Display mode for absorption
		#absorption.advanced.absorptionOverHealth must to be true
		#Modes:
		#  "BEGINNING":
		#    Absorption always starts at first heart.
		#  "AFTER_HEALTH":
		#    Absorption starts after the last highest health heart and loops back to first health heart if overflowing.
		#    This means that health hearts will be hidden when absorption has 10 or more hearts.
		#      Example 1: If a player has 10 health (5 hearts), absorption will render itself in the last
		#                   five hearts and in case it is higher it will loop back over first five health hearts.
		#      Example 2: If a player has more than 20 absorption, second color is shown the same way as in "BEGINNING".
		#      Example 3: If player health is divisible by 20, absorption is shown the same way as in "BEGINNING".
		#Allowed Values: BEGINNING, AFTER_HEALTH
		absorptionOverHealthMode = "AFTER_HEALTH"

