
[immersiveweapons-common]
	#Minimum distance in chunks between Landmine Traps - Default 6
	min_landmine_trap_distance = 10
	#Enable the natural spawning of Celestial Towers - Default true
	celestial_tower_spawn = true
	#Maximum distance in chunks between Pitfall Traps - Default 8
	max_pitfall_trap_distance = 8
	#Maximum distance in chunks between Bear Traps - Default 10
	max_bear_trap_distance = 16
	#Enable the Tiltros dimension portal - Default true
	tiltros_enabled = true
	#Minimum distance in chunks between Graveyards - Default 30
	min_water_tower_distance = 30
	#Minimum distance in chunks between Underground Bunkers - Default 80
	min_underground_bunker_distance = 80
	#Maximum distance in chunks between Abandoned Factories - Default 120
	max_abandoned_factory_distance = 120
	#Minimum distance in chunks between Pitfall Traps - Default 2
	min_pitfall_trap_distance = 2
	#Maximum distance in chunks between Graveyards - Default 50
	max_water_tower_distance = 50
	#Enable bullets breaking glass - Default true
	bullets_break_glass = true
	#Maximum distance in chunks between Battlefield Camps - Default 16
	max_battlefield_camp_distance = 20
	#Minimum distance in chunks between Battlefield Houses - Default 4
	min_battlefield_house_distance = 7
	#Set the Y spawn checking radius for the Celestial Tower.
	#Setting this higher will negatively impact server ticks in Tiltros, but make Celestial Lanterns more effective - Default 20
	celestial_tower_y_spawn_check_radius = 20
	#Enable the natural spawning of Dying Soldiers - Default true
	dying_soldiers_spawn = true
	#Multiplier to change the wave size from Celestial Tower summons.
	#Set less than 1 to reduce, greater than 1 to increase.
	#Increasing the wave size will negatively affect the server ticks in Tiltros. - Default 1.0
	celestial_tower_minions_wave_size_modifier = "1.0"
	#Minimum distance in chunks between Landmine Traps - Default 12
	max_landmine_trap_distance = 17
	#Set the maximum number of particles produced by the smoke bomb - Default 96
	#Setting this higher can make clients laggy, setting to 0 effectively disables it
	max_smoke_bomb_particles = 96
	#Maximum distance in chunks between Underground Bunkers - Default 110
	max_underground_bunker_distance = 110
	#Maximum distance in chunks between Battlefield Villages - Default 30
	max_battlefield_village_distance = 30
	#Maximum distance in chunks between Battlefield Houses - Default 12
	max_battlefield_house_distance = 15
	#Minimum distance in chunks between Battlefield Camps - Default 4
	min_battlefield_camp_distance = 8
	#Minimum distance in chunks between Outhouses - Default 20
	min_outhouse_distance = 20
	#Enable the natural spawning of Hans the Almighty - Default true
	hans_spawn = true
	#Enable the natural spawning of Wandering Warriors - Default true
	wandering_warriors_spawn = true
	#Set the X and Z spawn checking radius for the Celestial Tower.
	#Setting this higher will negatively impact server ticks in Tiltros, but make Celestial Lanterns more effective - Default 56
	celestial_tower_xz_spawn_check_radius = 56
	#Minimum distance in chunks between Campsites - Default 30
	min_campsite_distance = 40
	#Enable the natural spawning of Rock Spiders - Default true
	rock_spider_spawn = true
	#Minimum distance in chunks between Cloud Islands - Default 70
	min_cloud_island_distance = 80
	#Enable the Tesla Armor effect sound - Default true
	tesla_armor_effect_sound = true
	#Maximum distance in chunks between Campsites - Default 50
	max_campsite_distance = 60
	#Minimum distance in chunks between Abandoned Factories - Default 90
	min_abandoned_factory_distance = 90
	#Minimum distance in chunks between Bear Traps - Default 4
	min_bear_trap_distance = 9
	#Minimum distance in chunks between Battlefield Villages - Default 10
	min_battlefield_village_distance = 10
	#Maximum distance in chunks between Cloud Islands - Default 90
	max_cloud_island_distance = 100
	#Enable the natural spawning of Lava Revenants - Default true
	lava_revenant_spawn = true
	#Maximum distance in chunks between Outhouses - Default 40
	max_outhouse_distance = 40

