#Stop mods from adding custom flowers
flowers = true
#Stop mods from adding surface structures
surface_structures = false
#Stop mods from adding entities
entities = true
#Stop mods from adding lakes
lakes = false
#Main world id
main_world = "minecraft:overworld"

