
#Common changes
[common]
	#Lava monsters' maximum health.
	monsterHealth = 38.0
	#The amount of armor lava monsters have.
	monsterArmor = 7.0
	#The distance a lava monster will begin attacking. (maximum of 35)
	monsterRange = 17.0
	#Ticks a monster must wait after attacking before it can start winding up again.
	attackCooldown = 45
	#Number of fireballs shot with each attack.
	attackShots = 3
	#Ticks between each fireball shot in an attack.
	attackSpacing = 6
	#Ticks it takes before a monster can start an attack.
	attackWindup = 50

	#Spawning
	[common.spawning]
		#Allows you to choose which dimensions the Lava Monster spawns in. Add dimensions by their registry name/id, and separate them with commas, no spaces.
		dimensionWhitelist = "minecraft:overworld,minecraft:the_nether,good_nights_sleep:nightmare"
		#If enabled, the Lava Monster will instead use traditional vanilla spawning. 
		#This means the Lava Monster will attempt to spawn in groups, and less frequently, spawning significantly less frequently outside of lava-filled places like the Nether. 
		#This will remove any negative effects the classic Lava Monster spawning might have on server performance. 
		#However, due to the lack of spawns outside of places such as the Nether, and lack of configuration, this is disabled by default.
		shouldUseVanillaSpawning = false

		#Classic Spawning Options (Used when shouldUseVanillaSpawning is disabled)
		[common.spawning.classic_spawning]
			#If true, lava monsters will not spawn above layer 16. 
			#This will not take effect if the shouldUseVanillaSpawning option is enabled.
			depthHazard = false
			#If true, lava monsters do not require a source block to spawn. 
			#This will not take effect if the shouldUseVanillaSpawning option is enabled.
			flowingLava = false
			#If true, lava monsters will be able to spawn in lava one block deep. 
			#This will not take effect if the shouldUseVanillaSpawning option is enabled.
			shallowLava = false
			#The percentage chance for a lava monster spawn attempt to be successful. 1.0 means 100%. 
			#This will not take effect if the shouldUseVanillaSpawning option is enabled.
			spawnChance = 0.05
			#The number of ticks between each lava monster spawn attempt. 
			#This will not take effect if the shouldUseVanillaSpawning option is enabled.
			spawnFrequency = 20

