
# Legendary Tooltips Configuration Instructions
#
# *** READ THIS FIRST ***
#
# By default, this mod does not apply special borders to most items.  It was designed to work well with mod packs where
# the available selection of items can vary widely, so it is up to the user or mod pack designer to customize as needed.
# There are many options available for setting up which custom borders (also called frames) apply to which items.  Follow these steps:
#   1. Decide which items you want to have custom borders, and which borders.  Note that each custom border has a number associated with it (starting at 0).
#   2. For each custom border you want to use, fill out the associated list in the "definitions" section.  This will be filled out with a list of "selectors",
#      each of which tell the mod what items have that border.  Please read the information above the definitions section for specifics.
#   3. Selectors for borders are checked in the order provided in the "priorities" section.  Once a match is found, that border is displayed.
#      For example, if border 0 had the selector "%Diamond" and border 1 had the selector "diamond_sword", they would both match for diamond swords.
#      In this case, whichever border number came first in the priority list would be the border that would get drawn in-game.
#   4. Optionally, border colors associated with custom borders can be set in the "colors" section.  The start color is the color at the top of the tooltip,
#      and the end color is the bottom, with a smooth transition between.  Please read the information above the color section for specifics.
[client]

	[client.visual_options]
		# Whether item names in tooltips should have a line under them separating them from the rest of the tooltip.
		name_separator = true
		# If enabled, tooltip border colors will match item rarity colors (except for custom borders).
		borders_match_rarity = true
		# If enabled, tooltips will display a drop shadow.
		tooltip_shadow = true
		# If enabled, items showing a custom border will have a special shine effect when hovered over.
		shine_effect = true
		# If enabled, tooltip titles will be drawn centered.
		centered_title = false
		# If enabled, tooltips with custom borders will always be at least wide enough to display all border decorations.
		enforce_minimum_width = false

	# Entry types:
	#    Item name - Use item name for vanilla items or include mod name for modded items.  Examples: "minecraft:stick", "iron_ore"
	#    Tag - $ followed by tag name.  Examples: "$forge:stone", "$planks"
	#    Mod name - @ followed by mod identifier.  Examples: "@spoiledeggs"
	#    Rarity - ! followed by item's rarity.  This is ONLY vanilla rarities.  Examples: "!uncommon", "!rare", "!epic"
	#    Item name color - # followed by color hex code, the hex code must match exactly.  Examples: "#23F632"
	#    Display name - % followed by any text.  Will match any item with this text in its tooltip display name.  Examples: "%Netherite", "%[Uncommon]"
	#    Tooltip text - Will match any item with this text anywhere in the tooltip text (besides the name).  Examples: "^Legendary"
	#    NBT tag - & followed by tag name and optional comparator (=, >, <, or !=) and value, in the format <tag><comparator><value> or just <tag>.  Examples: "&Damage=0", "&Tier>1", "&map!=128", "&Enchantments"
	[client.definitions]
		level0_entries = ["kubejs:demon_pearl", "kubejs:star_of_sin", "kubejs:corrupted_emerald", "%Gobber End", "netherite_sword", "netherite_shovel", "netherite_pickaxe", "netherite_axe", "netherite_hoe", "netherite_helmet", "netherite_chestplate", "netherite_leggings", "netherite_boots"]
		level1_entries = ["%Gobber Nether", "experience_bottle", "golden_carrot", "golden_apple", "enchanted_golden_apple", "diamond_sword", "diamond_shovel", "diamond_pickaxe", "diamond_axe", "diamond_hoe", "diamond_helmet", "diamond_chestplate", "diamond_leggings", "diamond_boots", "enchanted_book", "turtle_helmet", "tipped_arrow", "spectral_arrow"]
		level2_entries = ["&Enchantments", "!rare", "iron_sword", "iron_shovel", "iron_pickaxe", "iron_axe", "iron_hoe", "iron_helmet", "iron_chestplate", "iron_leggings", "iron_boots", "golden_sword", "golden_shovel", "golden_pickaxe", "golden_axe", "golden_hoe", "golden_helmet", "golden_chestplate", "golden_leggings", "golden_boots", "%Chainmail", "compass", "clock", "spyglass", "shears", "%Bucket", "lead", "name_tag", "flint_and_steel", "bow", "crossbow", "trident", "shield"]
		level3_entries = ["$forge:ingots/crimson_iron", "%Nether B", "%Nether Q", "%Nether G", "netherrack", "%Nylium", "crimson_fungus", "warped_fungus", "campfire", "fire_charge", "%Firework", "%Lava", "@doom"]
		level4_entries = ["%Sea", "%Breathing", "sea_lantern", "heart_of_the_sea", "%Prismarine", "conduit", "nautilus_shell"]
		level5_entries = ["$minecraft:small_flowers", "$minecraft:flowers", "$minecraft:leaves", "$minecraft:saplings", "$minecraft:tall_flowers", "%Azalea", "%Dripleaf", "%Vines", "bamboo", "%Essence", "%Crop", "%Seed", "%Flower", "%Sapling", "%Bee", "%Honey"]
		level6_entries = ["%Dragon", "%Skull", "wither_rose", "%Obsidian", "respawn_anchor", "%Soul", "%Void"]
		level7_entries = ["iron_door", "iron_trapdoor", "iron_block", "%Anvil", "%Minecart", "%Rail", "hopper", "observer", "dispenser", "dropper", "%Piston", "$c:iron_ingots", "$forge:ingots/iron"]
		level8_entries = ["%End", "%Purpur", "%Chorus", "%Shulker", "%End Anchor"]
		level9_entries = ["%Angel Ring", "%Elytra", "elytra", "%Glow", "totem_of_undying"]
		level10_entries = []
		level11_entries = []
		level12_entries = []
		level13_entries = []
		level14_entries = []
		level15_entries = []
		# Enter blacklist selectors here using the same format as above. Any items that match these selectors will NOT show a border.
		blacklist = []

	# Set border priorities here.  This should be a list of numbers that correspond to border levels, with numbers coming first being higher priority.
	# Optionally, -1 can be inserted to indicate relative priority of data and api-defined borders.  If you don't know what that means, you don't need to worry about it.
	[client.priorities]
		priorities = [9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15]

	# The colors used for each tooltip, in this order: top border color, bottom border color, top background color, bottom background color.
	# None of these colors are required, though any colors not specified will be replaced with the default tooltip colors.
	#
	# VALID COLOR FORMATS
	#   Hex color code - A hex color code is preceded by # or 0x and must be quoted.  Supports 3, 4, 6, or 8 digit codes in the formats RGB, ARGB, RRGGBB, AARRGGBB.
	#     Examples: "#F4C", "0xFEE0", "#40FF2E", "#CC00E2EE"
	#
	#   Decimal color code - A decimal color code, which is just a hex color code converted to decimal.  May or may not be quoted.
	#     Examples: 15614720, "4278251143"
	#
	#   Minecraft color name - One of the standard 16 Minecraft color names.  Must be quoted.
	#     Examples: "red", "dark_purple", "gold"
	#
	#   Web color name - One of the standard 140 web/HTML color names or "transparent".  Must be quoted.
	#     Examples: "chartreuse", "darkorange", "deeppink", "deepskyblue"
	#
	#   Modifiers - Colors specified in any of the above formats can be modified by using modifiers.
	#         Modifiers are specified after any color in the format "<+, -, or =><h, s, v, r, g, b, or a><amount>".
	#         The letters represent h - hue, s - saturation, v - value, r - red, g - green, b - blue, a - alpha.
	#         Valid amounts are 0 to 255 for all types except hue, which accepts 0 to 359.
	#     Examples: "red+h15", "#saddlebrown-v20+s5", "10_aqua_aqua+v15-h5", "#F4C-r15-v10=a40"
	#
	#   Animated color - An animated color that fades from one to another in sequence.
	#         A string in the format "<duration in seconds>_<list of color definitions separated by underscores>".  Must be quoted.
	#     Examples: "10_black_#7FFF00", "5.5_gold_orange_orangered", "20_red_orange_yellow_green_blue_purple"
	[client.colors]
		level0_colors = ["#996922", "#5B3B1D", "#F0160A00", "#F0160A00"]
		level1_colors = ["#697C8C", "#3A4C61", "#F0160A00", "#F0160A00"]
		level2_colors = ["#70453D", "#542323", "#F0160A00", "#F0160A00"]
		level3_colors = ["#912307", "#818385", "#F0160A00", "#F0160A00"]
		level4_colors = ["#008FCC", "#044B8A", "#F0160A00", "#F0160A00"]
		level5_colors = ["#5C4C2D", "#5C4C2D", "#F0160A00", "#F0160A00"]
		level6_colors = ["#705A87", "#393556", "#F0160A00", "#F0160A00"]
		level7_colors = ["#7D8A91", "#7D8A91", "#F0160A00", "#F0160A00"]
		level8_colors = ["#A591B6", "#A591B6", "#F0160A00", "#F0160A00"]
		level9_colors = ["#FFFADB", "#FFDFAD", "#F0160A00", "#F0160A00"]
		level10_colors = ["#FF996922", "#FF5A3A1D", "#F0160A00", "#F0160A00"]
		level11_colors = ["#FF996922", "#FF5A3A1D", "#F0160A00", "#F0160A00"]
		level12_colors = ["#FF996922", "#FF5A3A1D", "#F0160A00", "#F0160A00"]
		level13_colors = ["#FF996922", "#FF5A3A1D", "#F0160A00", "#F0160A00"]
		level14_colors = ["#FF996922", "#FF5A3A1D", "#F0160A00", "#F0160A00"]
		level15_colors = ["#FF996922", "#FF5A3A1D", "#F0160A00", "#F0160A00"]

