
#Number of uses for each crystal
[Uses]
	#Durability for the Inferium Crystal
	#Range: > 1
	inferiumDurability = 96
	#Durability for the Prudentium Crystal
	#Range: > 1
	prudentiumDurability = 128
	#Durability for the Tertium Crystal
	#Range: > 1
	tertiumDurability = 256
	#Durability for the Imperium Crystal
	#Range: > 1
	imperiumDurability = 256
	#Durability for the Supremium Crystal
	#Range: > 1
	supremiumDurability = 256

#Whether or not crystals should have durability.
["Enable / Disable Durability"]
	#Should the Inferium Crystal Have Durability?
	inferiumDurabilityEnabled = true
	#Should the Prudentium Crystal Have Durability?
	prudentiumDurabilityEnabled = true
	#Should the Tertium Crystal Have Durability?
	tertiumDurabilityEnabled = true
	#Should the Imperium Crystal Have Durability?
	imperiumDurabilityEnabled = true
	#Should the Supremium Crystal Have Durability?
	supremiumDurabilityEnabled = true

