
[general]
	toggle = false
	rightClickToEdit = true
	releaseToSelect = false
	menuAnimation = true
	menuButtonIcon = "minecraft:diamond"

[visual]

	[visual.menu]
		#Range: 0 ~ 255
		alpha = 153
		#Range: 0 ~ 255
		red = 0
		#Range: 0 ~ 255
		green = 0
		#Range: 0 ~ 255
		blue = 0

	[visual.select]
		#Range: 0 ~ 255
		alpha = 153
		#Range: 0 ~ 255
		red = 255
		#Range: 0 ~ 255
		green = 0
		#Range: 0 ~ 255
		blue = 0

