
["Jungle Primates Spawn Weight"]
	#Spawn weight of Bonobos
	#Range: 0 ~ 1000
	bonobo_spawn_weight = 40
	#Spawn weight of Bush Babies
	#Range: 0 ~ 1000
	bush_baby_spawn_weight = 40
	#Spawn weight of Celebes
	#Range: 0 ~ 1000
	celebes_spawn_weight = 40
	#Spawn weight of Gibbons
	#Range: 0 ~ 1000
	gibbon_spawn_weight = 40
	#Spawn weight of Gigantopithecus's
	#Range: 0 ~ 1000
	gigantopithecus_spawn_weight = 10
	#Spawn weight of Howlers
	#Range: 0 ~ 1000
	howler_spawn_weight = 40
	#Spawn weight of Lemurs
	#Range: 0 ~ 1000
	lemur_spawn_weight = 40
	#Spawn weight of Loris's
	#Range: 0 ~ 1000
	loris_spawn_weight = 40
	#Spawn weight of Orangutans
	#Range: 0 ~ 1000
	orangutan_spawn_weight = 40
	#Spawn weight of Proboscis
	#Range: 0 ~ 1000
	proboscis_spawn_weight = 40
	#Spawn weight of Tamarins
	#Range: 0 ~ 1000
	tamarin_spawn_weight = 40
	#Spawn weight of Tarsiers
	#Range: 0 ~ 1000
	tarsier_spawn_weight = 40
	#Spawn weight of Uakaris
	#Range: 0 ~ 1000
	uakari_spawn_weight = 40
	#Spawn weight of Zombie apes
	#Range: 0 ~ 1000
	zombie_ape_spawn_weight = 25

["Savannah Primates Spawn Weight"]
	#Spawn weight of Baboons
	#Range: 0 ~ 1000
	baboon_spawn_weight = 40
	#Spawn weight of Geladas
	#Range: 0 ~ 1000
	gelada_spawn_weight = 40
	#Spawn weight of Mandrills
	#Range: 0 ~ 1000
	mandrill_spawn_weight = 40
	#Spawn weight of Hamadryas
	#Range: 0 ~ 1000
	hamadryas_spawn_weight = 40
	#Spawn weight of Rhesus's
	#Range: 0 ~ 1000
	rhesus_spawn_weight = 40

["Taiga Primates Spawn Weight"]
	#Spawn weight of Snub Nosed Monkeys
	#Range: 0 ~ 1000
	snub_nosed_monkey_spawn_weight = 40
	#Spawn weight of Bale Monkeys
	#Range: 0 ~ 1000
	bale_monkey_spawn_weight = 40
	#Spawn weight of Japanese Macaques
	#Range: 0 ~ 1000
	japanese_macaque_spawn_weight = 40

["Misc Primates and Others Spawn Weight"]
	#Spawn weight of Poacher
	#Range: 0 ~ 1000
	poacher_spawn_weight = 4

