
#General configuration options.
[General]
	#The percentage chance that a Wither will drop a Withering Soul when killed.
	#Range: 0.0 ~ 1.0
	witheringSoulChance = 0.1
	#The amount of Dragon Scales that an Ender Dragon will drop when killed.
	#Range: 0 ~ 64
	dragonScalesAmount = 1
	#Can tier 6 crops be fertilized using Mystical Fertilizer or Fertilized Essence?
	fertilizableTier6Crops = false
	#The duration of each Essence Apples effects in seconds.
	#Range: > 1
	essenceAppleDuration = 60

#World generation options.
[World]
	#Should Nether Prosperity Ore generate in the world?
	generateNetherProsperityOre = true
	#How many Nether Prosperity Ore veins should spawn in a chunk.
	#Range: > 0
	netherProsperitySpawnRate = 2
	#The maximum amount of Nether Prosperity Ore blocks that can spawn in a vein.
	#Range: > 0
	netherProsperitySpawnSize = 3
	#The minimum Y level that Nether Prosperity Ore veins can spawn.
	#Range: 0 ~ 128
	netherProsperitySpawnMinY = 25
	#The maximum Y level that Nether Prosperity Ore veins can spawn.
	#Range: 0 ~ 128
	netherProsperitySpawnMaxY = 50
	#Should Nether Inferium Ore generate in the world?
	generateNetherInferiumOre = true
	#How many Nether Inferium Ore veins should spawn in a chunk.
	#Range: > 0
	netherInferiumSpawnRate = 2
	#The maximum amount of Nether Inferium Ore blocks that can spawn in a vein.
	#Range: > 0
	netherInferiumSpawnSize = 3
	#The minimum Y level that Nether Inferium Ore veins can spawn.
	#Range: 0 ~ 128
	netherInferiumSpawnMinY = 66
	#The maximum Y level that Nether Inferium Ore veins can spawn.
	#Range: 0 ~ 128
	netherInferiumSpawnMaxY = 110
	#Should End Prosperity Ore generate in the world?
	generateEndProsperityOre = true
	#How many End Prosperity Ore veins should spawn in a chunk.
	#Range: > 0
	endProsperitySpawnRate = 2
	#The maximum amount of End Prosperity Ore blocks that can spawn in a vein.
	#Range: > 0
	endProsperitySpawnSize = 2
	#The minimum Y level that Prosperity Ore veins can spawn.
	#Range: 0 ~ 128
	endProsperitySpawnMinY = 10
	#The maximum Y level that Prosperity Ore veins can spawn.
	#Range: 0 ~ 128
	endProsperitySpawnMaxY = 45
	#Should End Inferium Ore generate in the world?
	generateEndInferiumOre = true
	#How many End Inferium Ore veins should spawn in a chunk.
	#Range: > 0
	endInferiumSpawnRate = 2
	#The maximum amount of End Inferium Ore blocks that can spawn in a vein.
	#Range: > 0
	endInferiumSpawnSize = 2
	#The minimum Y level that End Inferium Ore veins can spawn.
	#Range: 0 ~ 128
	endInferiumSpawnMinY = 55
	#The maximum Y level that End Inferium Ore veins can spawn.
	#Range: 0 ~ 128
	endInferiumSpawnMaxY = 100

