
#General configuration options.
[General]
	#The percentage chance that a Wither will drop a Withering Soul when killed.
	#Range: 0.0 ~ 1.0
	witheringSoulChance = 0.075
	#The amount of Dragon Scales that an Ender Dragon will drop when killed.
	#Range: 0 ~ 64
	dragonScalesAmount = 1
	#Can tier 6 crops be fertilized using Mystical Fertilizer or Fertilized Essence?
	fertilizableTier6Crops = false
	#The duration of each Essence Apples effects in seconds.
	#Range: > 1
	essenceAppleDuration = 60
	#Should Cruxes for disabled crops be hidden and not have recipes?
	hideUnusedCruxes = true

#World generation options.
[World]
	#Should Nether Prosperity Ore generate in the world?
	generateNetherProsperityOre = true
	#How many Nether Prosperity Ore veins should spawn in a chunk.
	#Range: > 0
	netherProsperitySpawnRate = 4
	#The maximum amount of Nether Prosperity Ore blocks that can spawn in a vein.
	#Range: > 0
	netherProsperitySpawnSize = 3
	#The minimum Y level that Nether Prosperity Ore veins can spawn.
	#Range: 0 ~ 128
	netherProsperitySpawnMinY = 30
	#The maximum Y level that Nether Prosperity Ore veins can spawn.
	#Range: 0 ~ 128
	netherProsperitySpawnMaxY = 60
	#Should Nether Inferium Ore generate in the world?
	generateNetherInferiumOre = true
	#How many Nether Inferium Ore veins should spawn in a chunk.
	#Range: > 0
	netherInferiumSpawnRate = 4
	#The maximum amount of Nether Inferium Ore blocks that can spawn in a vein.
	#Range: > 0
	netherInferiumSpawnSize = 4
	#The minimum Y level that Nether Inferium Ore veins can spawn.
	#Range: 0 ~ 128
	netherInferiumSpawnMinY = 40
	#The maximum Y level that Nether Inferium Ore veins can spawn.
	#Range: 0 ~ 128
	netherInferiumSpawnMaxY = 90
	#Should End Prosperity Ore generate in the world?
	generateEndProsperityOre = false
	#How many End Prosperity Ore veins should spawn in a chunk.
	#Range: > 0
	endProsperitySpawnRate = 3
	#The maximum amount of End Prosperity Ore blocks that can spawn in a vein.
	#Range: > 0
	endProsperitySpawnSize = 2
	#The minimum Y level that Prosperity Ore veins can spawn.
	#Range: 0 ~ 128
	endProsperitySpawnMinY = 10
	#The maximum Y level that Prosperity Ore veins can spawn.
	#Range: 0 ~ 128
	endProsperitySpawnMaxY = 50
	#Should End Inferium Ore generate in the world?
	generateEndInferiumOre = false
	#How many End Inferium Ore veins should spawn in a chunk.
	#Range: > 0
	endInferiumSpawnRate = 3
	#The maximum amount of End Inferium Ore blocks that can spawn in a vein.
	#Range: > 0
	endInferiumSpawnSize = 2
	#The minimum Y level that End Inferium Ore veins can spawn.
	#Range: 0 ~ 128
	endInferiumSpawnMinY = 50
	#The maximum Y level that End Inferium Ore veins can spawn.
	#Range: 0 ~ 128
	endInferiumSpawnMaxY = 100

