
#General mod settings
[general]
	#Range: 1.0 ~ 30000.0
	tileEntityRenderRangeMax = 17.0
	#Range: 1.0 ~ 30000.0
	entityRenderRangeMax = 50.0
	tileEntityRenderLimitModdedOnly = true
	entityRenderLimitModdedOnly = true

