
#Planes settings
[general]
	#For controllers, a threshold for the joystick movement of the plane
	#Range: 0 ~ 90
	turnThreshold = 20
	#Allow stealing planes by players
	plane_heist = false
	#Fuel cost of a small plane
	#Range: > 0
	plane_fuel_cost = 6
	#Fuel cost of a large plane
	#Range: > 0
	large_plane_fuel_cost = 10
	#Fuel cost of a helicopter
	#Range: > 0
	helicopter_fuel_cost = 9

