
#ToolKit common config
[playerEvent]
	#Send messages to users on join?
	message_on_join = true
	#if messageOnJoin is true this message will be send to the player on joining world
	message = "Another Quality Modpack 3 Discord @ https://discord.gg/aqm2"

