
[general]
	#Enable that penguins drop fish (0 - 2 Raw Cod)
	dropFish = true
	#Penguins should drop experience?
	dropExp = true
	#Use the Darkosto skin variant by default?
	darkostoDefault = true
	"spawn blocks" = ["minecraft:grass_block", "minecraft:snow_block"]

["spawn chances"]
	#Configure penguins spawn weight & min/max group size. Set weight to 0 to disable.
	#Range: 0 ~ 64
	min = 1
	#Range: 0 ~ 64
	max = 4
	#Range: 0 ~ 100
	weight = 8

["spawnable biomes"]
	include = ["SNOWY"]
	exclude = ["FOREST", "MOUNTAIN", "OCEAN", "NETHER"]

