
[world_gen]
	#Config to toggle the generation of arms in snow biomes
	arms = true
	#Configure whether the mods ores spawn. This MAY require a restart when changed.
	genOres = true
	#Configure whether Graveyard Structures spawn. This will require a restart when changed.
	genGraveyard = true
	#Configure whether Catacombs Structures spawn. This will require a restart when changed.
	genCatacombs = true

[spawn]
	#The minimum amount of angels per biome
	#Range: 1 ~ 100
	minimumSpawn = 1
	#The maximum amount of angels per biome
	#Range: 1 ~ 100
	maximumSpawn = 3
	#The angel spawn spawn weight
	#Range: 1 ~ 100
	spawnWeight = 4
	#Angel spawn type
	#Allowed Values: MONSTER, CREATURE, AMBIENT, AXOLOTLS, UNDERGROUND_WATER_CREATURE, WATER_CREATURE, WATER_AMBIENT, MISC
	spawnType = "MONSTER"
	#Note: A list of biomes where angels should spawn.
	allowedBiomes = ["minecraft:the_void", "minecraft:plains", "minecraft:sunflower_plains", "minecraft:snowy_plains", "minecraft:ice_spikes", "minecraft:desert", "minecraft:swamp", "minecraft:forest", "minecraft:flower_forest", "minecraft:birch_forest", "minecraft:dark_forest", "minecraft:old_growth_birch_forest", "minecraft:old_growth_pine_taiga", "minecraft:old_growth_spruce_taiga", "minecraft:taiga", "minecraft:snowy_taiga", "minecraft:savanna", "minecraft:savanna_plateau", "minecraft:windswept_hills", "minecraft:windswept_gravelly_hills", "minecraft:windswept_forest", "minecraft:windswept_savanna", "minecraft:jungle", "minecraft:sparse_jungle", "minecraft:bamboo_jungle", "minecraft:badlands", "minecraft:eroded_badlands", "minecraft:wooded_badlands", "minecraft:meadow", "minecraft:grove", "minecraft:snowy_slopes", "minecraft:frozen_peaks", "minecraft:jagged_peaks", "minecraft:stony_peaks", "minecraft:river", "minecraft:frozen_river", "minecraft:beach", "minecraft:snowy_beach", "minecraft:stony_shore", "minecraft:warm_ocean", "minecraft:lukewarm_ocean", "minecraft:deep_lukewarm_ocean", "minecraft:ocean", "minecraft:deep_ocean", "minecraft:cold_ocean", "minecraft:deep_cold_ocean", "minecraft:frozen_ocean", "minecraft:deep_frozen_ocean", "minecraft:mushroom_fields", "minecraft:dripstone_caves", "minecraft:lush_caves", "minecraft:nether_wastes", "minecraft:warped_forest", "minecraft:crimson_forest", "minecraft:soul_sand_valley", "minecraft:basalt_deltas", "minecraft:the_end", "minecraft:end_highlands", "minecraft:end_midlands", "minecraft:small_end_islands", "minecraft:end_barrens"]

[angel]
	#Damage Type For Angels
	#Allowed Values: NOTHING, ANY_PICKAXE_AND_GENERATOR_ONLY, ANY_PICKAXE_ONLY, DIAMOND_AND_ABOVE_PICKAXE_ONLY, GENERATOR_ONLY
	damageType = "ANY_PICKAXE_AND_GENERATOR_ONLY"
	#Non-child angels play scraping sounds when moving, this toggles that
	playScrapeSound = true
	#Toggle seen sounds
	playSeenSounds = true
	#The damage dealt by an angel
	#Range: 1.0 ~ 1.7976931348623157E308
	damage = 8.6
	#XP gained from angels
	#Range: > 1
	xpGained = 44
	#If this is enabled, the timey wimey detector can blow up chickens when in use randomly
	chickenGoboom = true
	#If this is enabled, baby angels will blow out light items from the players hand
	torchBlowOut = true
	#if enabled, angels will freeze when they see one another. (Impacts performance a bit)
	freezeOnAngel = false
	#if enabled, Only pickaxes and generators will work on the angels
	pickaxeOnly = true
	#Determines the range the angels will look for players within, personally, I'd stay under 100
	#Range: 1 ~ 100
	stalkRange = 65
	#Determines the angels move speed
	#Range: 0.1 ~ 1.7976931348623157E308
	angelMovementSpeed = 0.22
	#If this is enabled, angels will break blocks (If gamerules allow)
	blockBreaking = true
	#The maximum range a angel can break blocks within
	#Range: 1 ~ 120
	blockBreakRange = 11

[teleport]
	#Teleport Type - STRUCTURES: Teleports you to Structures Only - DONT: No Teleporting, only damage - RANDOM: Anywhere
	#Allowed Values: STRUCTURES, RANDOM_PLACE, DONT
	teleportType = "RANDOM_PLACE"
	#Note: This a list of dimensions that angels should NOT teleport you to.
	notAllowedDimensions = ["minecraft:the_end"]
	#just teleport. no damage.
	justTeleport = false
	#The maximum range a user can be teleported by the Angels
	#Range: > 1
	teleportRange = 450
	#If this is enabled, angel teleporting can also tp the player to other dimensions
	angelDimTeleport = true
	#Should Angels target creative players?
	aggroCreative = true

[block]
	#This config option toggles whether angels can spawn from Statues/Plinths when they receive a redstone signal
	spawnFromBlocks = true

[misc]
	#Toggle whether santa hats are shown at Xmas
	showSantaHatsAtXmas = true
	#Toggle certain angel models (Only applies to Entity)
	allowedAngelTypes = ["DISASTER_MC", "DOCTOR", "ED", "ED_ANGEL_CHILD", "A_DIZZLE", "DYING", "VILLAGER"]
	#Toggle certain angel variants (Only applies to Entity)
	allowedVariants = ["weeping_angels:gold", "weeping_angels:diamond", "weeping_angels:iron", "weeping_angels:mossy", "weeping_angels:normal", "weeping_angels:basalt", "weeping_angels:rusted", "weeping_angels:rusted_no_arm", "weeping_angels:rusted_no_wing", "weeping_angels:rusted_no_head", "weeping_angels:dirt", "weeping_angels:emerald", "weeping_angels:copper", "weeping_angels:lapis_lazuli", "weeping_angels:quartz"]

