
[VisualEffects]
	#Should the Enchanted Book has a different texture when it has any of the Wonderful Enchantments on it? (disabling it may fix some bugs with other mods) (requires world/game restart)
	enchantment_book_replacement = true
	#Should the Enchanted Book has a different texture when it has any of the Wonderful Enchantments and other enchantments on it? (disabling it may fix some bugs with other mods) (requires world/game restart)
	combined_book_replacement = true

