
#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for Repurposed Structures Shipwrecks.
# 1 for spawning in most chunks and 1001 for none.
[Shipwrecks]
	#Range: 1 ~ 1001
	endShipwreckAverageChunkDistance = 24
	#Range: 1 ~ 1001
	netherBricksShipwreckAverageChunkDistance = 21
	#Range: 1 ~ 1001
	crimsonShipwreckAverageChunkDistance = 18
	#Range: 1 ~ 1001
	warpedShipwreckAverageChunkDistance = 18

