
#
# Average distance between spawn attempts for Repurposed Structures Temples.
# 1 for spawning in most chunks and 1001 for none.
[Temples]
	#Range: 1 ~ 1001
	netherWastelandTempleAverageChunkDistance = 36
	#Range: 1 ~ 1001
	netherBasaltTempleAverageChunkDistance = 36
	#Range: 1 ~ 1001
	netherCrimsonTempleAverageChunkDistance = 36
	#Range: 1 ~ 1001
	netherWarpedTempleAverageChunkDistance = 36
	#Range: 1 ~ 1001
	netherSoulTempleAverageChunkDistance = 36

